#ifndef NTAU__TRACKREADERCLASS__H
#define NTAU__TRACKREADERCLASS__H

/// Autogenerated code by NtupleBranchMgr on Thu Sep  1 13:01:05 2022


#include "NtupleAnalysisUtils/NTAUTopLevelIncludes.h"
#include <vector>
#include "TTree.h"

class TrackReaderClass: public NtupleBranchMgr{
    public:
        TrackReaderClass(TTree* t): NtupleBranchMgr(t){
            if(t) getMissedBranches(t);
        }
     /// List of branch members
        NtupleBranch <UInt_t>                       event_id{"event_id",        m_tree, this};
        NtupleBranch <Int_t>                        nTracks{"nTracks",         m_tree, this};
        NtupleBranch <std::vector < Int_t>>         track_index{"track_index",     m_tree, this};
        NtupleBranch <std::vector < Int_t>>         track_road_index{"track_road_index",m_tree, this};
        NtupleBranch <std::vector < Int_t>>         track_nHits{"track_nHits",     m_tree, this};
        NtupleBranch <std::vector < std::vector<Int_t>>>track_hit_indices{"track_hit_indices",m_tree, this};
        NtupleBranch <std::vector < ULong64_t>>     track_truth_match_index{"track_truth_match_index",m_tree, this};
        NtupleBranch <std::vector < Float_t>>       track_truth_match_fraction{"track_truth_match_fraction",m_tree, this};
};
#endif // NTAU__TRACKREADERCLASS__H
