#ifndef NTAU__HTTTRUTHTREE__H
#define NTAU__HTTTRUTHTREE__H

/// Autogenerated code by NtupleBranchMgr on Mon Jul 10 04:53:34 2023


#include "NtupleAnalysisUtils/NTAUTopLevelIncludes.h"
#include <vector>
#include "TTree.h"

class HTTTruthTree: public NtupleBranchMgr{
    public:
        HTTTruthTree(TTree* t): NtupleBranchMgr(t){
            if(t) getMissedBranches(t);
        }
     /// List of branch members
        NtupleBranch <std::vector < Float_t>>       truth_d0{"truth_d0",        m_tree, this};
        NtupleBranch <std::vector < Float_t>>       truth_z0{"truth_z0",        m_tree, this};
        NtupleBranch <std::vector < Float_t>>       truth_pt{"truth_pt",        m_tree, this};
        NtupleBranch <std::vector < Float_t>>       truth_eta{"truth_eta",       m_tree, this};
        NtupleBranch <std::vector < Float_t>>       truth_phi{"truth_phi",       m_tree, this};
        NtupleBranch <std::vector < Int_t>>         truth_q{"truth_q",         m_tree, this};
        NtupleBranch <std::vector < Float_t>>       truth_pdg{"truth_pdg",       m_tree, this};
        NtupleBranch <std::vector < Int_t>>         truth_barcode{"truth_barcode",   m_tree, this};
        NtupleBranch <std::vector < Int_t>>         truth_eventindex{"truth_eventindex",m_tree, this};
};
#endif // NTAU__HTTTRUTHTREE__H
