#ifndef NTAU__RECOTRACKSATLAS__H
#define NTAU__RECOTRACKSATLAS__H

/// Autogenerated code by NtupleBranchMgr on Mon Jul 10 04:25:45 2023


#include "NtupleAnalysisUtils/NTAUTopLevelIncludes.h"
#include <vector>
#include "TTree.h"

class RecoTracksATLAS: public NtupleBranchMgr{
    public:
        RecoTracksATLAS(TTree* t): NtupleBranchMgr(t){
            if(t) getMissedBranches(t);
        }
     /// List of branch members
        NtupleBranch <std::vector < Float_t>>       track_Pt{"track_Pt",        m_tree, this};
        NtupleBranch <std::vector < Float_t>>       track_Eta{"track_Eta",       m_tree, this};
        NtupleBranch <std::vector < Float_t>>       track_phi{"track_phi",       m_tree, this};
        NtupleBranch <std::vector < Float_t>>       track_truthProb{"track_truthProb", m_tree, this};
        NtupleBranch <std::vector < Int_t>>         track_index{"track_index",     m_tree, this};
        NtupleBranch <std::vector < Int_t>>         track_charge{"track_charge",    m_tree, this};
        NtupleBranch <std::vector < Int_t>>         track_nHits{"track_nHits",     m_tree, this};
        NtupleBranch <std::vector < Int_t>>         track_nPixHits{"track_nPixHits",  m_tree, this};
        NtupleBranch <std::vector < Int_t>>         track_nSCTHits{"track_nSCTHits",  m_tree, this};
        NtupleBranch <std::vector < std::vector<Int_t>>>track_clusterIndex{"track_clusterIndex",m_tree, this};
        NtupleBranch <std::vector < Int_t>>         track_truthTrackBarcode{"track_truthTrackBarcode",m_tree, this};
        NtupleBranch <std::vector < Float_t>>       track_perigee_d0{"track_perigee_d0",m_tree, this};
        NtupleBranch <std::vector < Float_t>>       track_perigee_z0{"track_perigee_z0",m_tree, this};
        NtupleBranch <std::vector < Float_t>>       track_perigee_phi{"track_perigee_phi",m_tree, this};
        NtupleBranch <std::vector < Float_t>>       track_perigee_theta{"track_perigee_theta",m_tree, this};
        NtupleBranch <std::vector < Float_t>>       track_perigee_qp{"track_perigee_qp",m_tree, this};
};
#endif // NTAU__RECOTRACKSATLAS__H
